name: example
description: Tradutor example.
version: 0.1.0

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
    flutter:
      sdk: flutter
    flutter_localizations:
      sdk: flutter

dev_dependencies:
  tradutor:
    path: ../
