name: tradutor
description: A Flutter package that simplify the internationalizing process using JSON and YAML files.
version: 0.9.2
homepage: https://github.com/tiagohm/tradutor

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  path: ^1.6.4
  dart_style: ^1.3.6
  stream_transform: ^1.2.0
  yaml: ^2.2.1
  code_builder: ^3.3.0
  equatable: ^1.2.0
  args: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  effective_dart: ^1.2.3
