name: tradutor
description: A Flutter package that simplify the internationalizing process using JSON and YAML files.
version: 0.6.2
homepage: https://github.com/tiagohm/tradutor

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  args: ^1.5.2
  path: ^1.6.4
  dart_style: ^1.3.6
  ansicolor: ^1.0.2
  stream_transform: ^1.2.0
  yaml: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
