name: tradutor
description: A new Flutter package project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  args: ^1.5.2
  path: ^1.6.2
  dart_style: ^1.2.9
  ansicolor: ^1.0.2
  stream_transform: ^0.0.19

dev_dependencies:
  flutter_test:
    sdk: flutter
  
flutter:
